core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('estoque/', include('estoque.urls')),
    path('lojas/', include('lojas.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('produtos/', include('produtos.urls')),
    path('', include('autenticacao.urls')),
]

estoque/urls.py
from django.urls import path
from . import views

app_name = 'estoque'

urlpatterns = [
    # Produtos
    path('produtos/', views.ProdutoListView.as_view(), name='produto_list'),
    path('produtos/novo/', views.ProdutoCreateView.as_view(), name='produto_create'),
    path('produtos/<int:pk>/editar/', views.ProdutoUpdateView.as_view(), name='produto_update'),
    path('produtos/<int:pk>/', views.ProdutoDetailView.as_view(), name='produto_detail'),
    
]

lojas/urls.py
from django.urls import path
from . import views
from .views import CadastroLojaView, AjustarEstoqueView, HistoricoEstoqueView

app_name = 'lojas'

urlpatterns = [
    path('produtos/', views.ProdutosDisponiveisView.as_view(), name='produtos_disponiveis'),
    path('estoque/', views.EstoqueLojaView.as_view(), name='estoque_loja'),
    path('cadastro/', CadastroLojaView.as_view(), name='cadastro_loja'),
    path('historico/', HistoricoEstoqueView.as_view(), name='historico_estoque'),
    path('ajustar/<int:pk>/', AjustarEstoqueView.as_view(), name='ajustar_estoque'),
]

pedidos/urls.py
from django.urls import path
from .views import CriarPedidoView, ListaPedidosView, DetalhePedidoView, ListaPedidosAdminView, DetalhePedidoAdminView, AlterarStatusView

app_name = 'pedidos'

urlpatterns = [
    path('pedidos/', CriarPedidoView.as_view(), name='criar_pedido'),
    path('lista/', ListaPedidosView.as_view(), name='lista_pedidos'),
    path('<int:pk>/', DetalhePedidoView.as_view(), name='detalhe_pedido'),

    path('lista_pedidos_admin/', ListaPedidosAdminView.as_view(), name='lista_pedidos_admin'),
    path('admin/<int:pk>/', DetalhePedidoAdminView.as_view(), name='detalhe_pedido_admin'),
    path('alterar-status/<int:pk>/', AlterarStatusView.as_view(), name='alterar_status'),
]


produtos/urls.py
from django.urls import path
from .views import CadastrarProdutoView, ImportarProdutosView, download_modelo_importacao, EditarProdutoView


app_name = 'produtos'

urlpatterns = [
    path('cadastrar/', CadastrarProdutoView.as_view(), name='cadastrar'),
    path('importar/', ImportarProdutosView.as_view(), name='importar_produtos'),
    path('importar/modelo/', download_modelo_importacao, name='download_modelo'),
    path('editar/<int:pk>/', EditarProdutoView.as_view(), name='produto_update'),
]




estoque/models.py
from django.db import models

# Create your models here.

estoque/forms.py
from django import forms
from django.forms import inlineformset_factory
from produtos.models import Produto
from pedidos.models import Pedido, ItemPedido

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['codigo', 'ean', 'descricao', 'cor', 'tamanho', 'quantidade']
        widgets = {
            'descricao': forms.Textarea(attrs={'rows': 2}),
        }

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['observacoes']
        widgets = {
            'observacoes': forms.Textarea(attrs={'rows': 3}),
        }

ItemPedidoFormSet = inlineformset_factory(
    Pedido,
    ItemPedido,
    fields=('produto', 'quantidade'),
    extra=1,
    can_delete=True,
    widgets={
        'produto': forms.Select(attrs={'class': 'select2'}),
    }
)

estoque/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from produtos.models import Produto
from pedidos.models import Pedido, ItemPedido
from .forms import ProdutoForm, PedidoForm, ItemPedidoFormSet

## Views para Produtos ##

class ProdutoListView(LoginRequiredMixin, ListView):
    model = Produto
    template_name = 'estoque/produto_list.html'
    context_object_name = 'produtos'
    paginate_by = 20
    
    def get_queryset(self):
        queryset = super().get_queryset()
        # Filtro por busca
        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(descricao__icontains=search) | queryset.filter(codigo__icontains=search)
        return queryset.order_by('descricao')

class ProdutoCreateView(LoginRequiredMixin, CreateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'estoque/produto_form.html'
    success_url = reverse_lazy('estoque:produto_list')
    
    def form_valid(self, form):
        messages.success(self.request, 'Produto cadastrado com sucesso!')
        return super().form_valid(form)

class ProdutoUpdateView(LoginRequiredMixin, UpdateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'estoque/produto_form.html'
    success_url = reverse_lazy('estoque:produto_list')
    
    def form_valid(self, form):
        messages.success(self.request, 'Produto atualizado com sucesso!')
        return super().form_valid(form)

class ProdutoDetailView(LoginRequiredMixin, DetailView):
    model = Produto
    template_name = 'estoque/produto_detail.html'
    context_object_name = 'produto'

## Views para Pedidos ##

class PedidoListView(LoginRequiredMixin, ListView):
    model = Pedido
    template_name = 'estoque/pedido_list.html'
    context_object_name = 'pedidos'
    paginate_by = 15
    
    def get_queryset(self):
        queryset = super().get_queryset()
        status = self.request.GET.get('status')
        if status:
            queryset = queryset.filter(status=status)
        return queryset.order_by('-data_criacao')

class PedidoCreateView(LoginRequiredMixin, CreateView):
    model = Pedido
    form_class = PedidoForm
    template_name = 'estoque/pedido_form.html'
    success_url = reverse_lazy('estoque:pedido_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['itens_formset'] = ItemPedidoFormSet(self.request.POST)
        else:
            context['itens_formset'] = ItemPedidoFormSet()
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        itens_formset = context['itens_formset']
        
        if itens_formset.is_valid():
            self.object = form.save()
            itens_formset.instance = self.object
            itens_formset.save()
            messages.success(self.request, 'Pedido criado com sucesso!')
            return redirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))

class PedidoUpdateView(LoginRequiredMixin, UpdateView):
    model = Pedido
    form_class = PedidoForm
    template_name = 'estoque/pedido_form.html'
    
    def get_success_url(self):
        return reverse_lazy('estoque:pedido_detail', kwargs={'pk': self.object.pk})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['itens_formset'] = ItemPedidoFormSet(self.request.POST, instance=self.object)
        else:
            context['itens_formset'] = ItemPedidoFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        itens_formset = context['itens_formset']
        
        if itens_formset.is_valid():
            response = super().form_valid(form)
            itens_formset.instance = self.object
            itens_formset.save()
            messages.success(self.request, 'Pedido atualizado com sucesso!')
            return response
        else:
            return self.render_to_response(self.get_context_data(form=form))

class PedidoDetailView(LoginRequiredMixin, DetailView):
    model = Pedido
    template_name = 'estoque/pedido_detail.html'
    context_object_name = 'pedido'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['itens'] = self.object.itens.all().select_related('produto')
        return context

def atualizar_status_pedido(request, pk, status):
    pedido = get_object_or_404(Pedido, pk=pk)
    pedido.status = status
    pedido.save()
    messages.success(request, f'Status do pedido {pedido.numero_pedido} atualizado para {pedido.get_status_display()}')
    return redirect('estoque:pedido_detail', pk=pedido.pk)



estoque/templates/estoque/produto_list.html
{% extends "base.html" %}
{% load static %}


<!-- Sidebar
<aside class="col-md-3 mb-4">
<div class="card">
    <div class="card-header bg-light">
        Menu
    </div>
    <div class="list-group list-group-flush">
        <a href="{% url 'estoque:produto_list' %}" 
            class="list-group-item list-group-item-action {% if 'produto' in request.path %}active{% endif %}">
            <i class="fas fa-box me-2"></i> Produtos
        </a>
        <a href="{% url 'pedidos:lista_pedidos_admin' %}" 
            class="list-group-item list-group-item-action {% if 'pedido' in request.path %}active{% endif %}">
            <i class="fas fa-clipboard-list me-2"></i> Pedidos
        </a>
        <a href="#" class="list-group-item list-group-item-action">
            <i class="fas fa-chart-bar me-2"></i> Relatórios
        </a>
    </div>
</div>
</aside> -->

{% block content %}

<div class="container-fluid">
    <div class="row">
 

        <!-- Conteúdo principal -->
        <main class="col-md-9">
            <h2>Lista de Produtos</h2>
            
            <div class="mb-3">
                <a href="{% url 'produtos:cadastrar' %}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Novo Produto
                </a>
                
                <a href="{% url 'produtos:importar_produtos' %}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Importar Produtos
                </a>

                <a href="{% url 'pedidos:lista_pedidos_admin' %}" class="btn btn-primary">
                    Listar Pedidos
                </a>
                <a href="{% url 'lojas:historico_estoque' %}" class="btn btn-primary">
                    Historico
                </a>
            </div>


            <form method="get" class="mb-4">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Buscar por código ou descrição" value="{{ request.GET.search }}">
                    <button type="submit" class="btn btn-outline-secondary">Buscar</button>
                </div>
            </form>
            
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Cor/Tamanho</th>
                        <th>Estoque</th>
                        <th>SellIn</th>
                        <th>SellOut</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for produto in produtos %}
                    <tr>
                        <td>{{ produto.codigo }}</td>
                        <td>{{ produto.descricao }}</td>
                        <td>
                            {% if produto.cor %}{{ produto.cor }}{% endif %}
                            {% if produto.tamanho %}/ {{ produto.tamanho }}{% endif %}
                        </td>
                        <td>{{ produto.quantidade }}</td>
                        <td>{{ produto.preco_sellin }}</td>
                        <td>{{ produto.preco_sellout }}</td>
                        <td>
                            <a href="{% url 'produtos:produto_update' produto.pk %}" class="btn btn-sm btn-warning">Editar</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">Nenhum produto encontrado</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </div>
</div>
{% endblock %}